apiVersion: apps/v1
kind: Deployment
metadata:
  name: gost
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gost
  template:
    metadata:
      labels:
        app: gost
    spec:
      volumes:
        - name: gost-vl
          configMap:
            name: gost.yaml
            items:
              - key: gost.yaml
                path: gost.yaml
      containers:
        - name: gost
          image: omaidb/gost:latest
          resources:
            limits:
              memory: "25Mi"
              cpu: "10m"
          volumeMounts:
            - mountPath: "/app/gost.yaml"
              subPath: gost.yaml
              name: gost-vl
