apiVersion: v1
kind: Service
metadata:
  name: gost
spec:
  selector:
    app: gost
  ports:
    - name: tcp
      protocol: UDP
      port: 1080
      targetPort: 1080
    - name: udp
      protocol: TCP
      port: 1080
      targetPort: 1080
  type: NodePort
