apiVersion: v1
kind: Service
metadata:
  name: openai-realm
spec:
  ports:
    - port: 443
      name: tcp
      protocol: TCP
      targetPort: 443
  selector:
    app: openai-realm
  type: NodePort