apiVersion: v1
kind: Service
metadata:
  name: wg-realm
spec:
  ports:
    - port: 514
      name: udp
      protocol: UDP
      targetPort: 514
  selector:
    app: wg-realm
  type: NodePort
