apiVersion: v1
kind: Pod
metadata:
  name: ocserv-tcp
  labels:
    name: ocserv-tcp
spec:
  restartPolicy: Always
  volumes:
    - name: coserv-vl
      configMap:
        name: coserv-tcp
  containers:
    - name: gost
      image: omaidb/gost:3.0.0-rc6
      resources:
        limits:
          memory: "20Mi"
          cpu: "50m"
      ports:
        - containerPort: 443
      volumeMounts:
        - mountPath: "/app/"
          name: ocserv-vl
