# 集群配置文件示例
apiVersion: v1
kind: Config

# 配置多个集群名称
clusters:
  - cluster:
      certificate-authority: { 使用base64加密的证书内容 }
      server: https://{api地址}:6443
    # K8s集群的名称
    name: kubernetes

# 连接集群使用的用户
users:
  # 用户名
  - name: kubernetes-admin
    user:
      client-certificate-data: { 使用base64加密的证书内容 }
      client-key-data: { 使用base64加密的key内容 }

# 上下文--将users和集群关联起来
contexts:
  - context:
      # 集群名字
      cluster: kubernetes
      # 关联的用户名
      user: kubernetes-admin
    # 上下文name(固定格式): users@集群名
    name: kubernetes-admin@kubernetes

# 当前上下文---声明当前所连接的集群
# current-context: 当前所要使用的上下文name
current-context: kubernetes-admin@kubernetes
