apiVersion: v1
kind: Service
metadata:
  name: gost-realm
spec:
  selector:
    app: gost-realm
  ports:
    - name: tcp
      port: 1080
      protocol: TCP
      targetPort: 1080
    - name: udp
      port: 1080
      protocol: UDP
      targetPort: 1080
  type: NodePort
